# Generated by Django 3.2 on 2021-04-20 16:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import tickets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=100, verbose_name='Long Name')),
                ('short_name', models.CharField(max_length=50, verbose_name='Short Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('email_address', models.EmailField(max_length=254, verbose_name='email Address')),
                ('new_ticket_cc', models.CharField(blank=True, max_length=255, null=True, verbose_name='New Ticket CC Address')),
                ('updated_ticket_cc', models.CharField(blank=True, max_length=255, null=True, verbose_name='Updated Ticket CC Address')),
                ('dedicated_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Container',
                'verbose_name_plural': 'Containers',
                'ordering': ('long_name',),
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Email Username')),
                ('password', models.CharField(max_length=30, verbose_name='Email Password')),
                ('email_type', models.CharField(choices=[('pop3', 'POP 3'), ('imap', 'IMAP')], default='imap', max_length=5, verbose_name='Email Type')),
                ('host', models.CharField(max_length=30, verbose_name='Host Name')),
                ('port', models.IntegerField(default=993, verbose_name='Email Port')),
                ('ssl', models.BooleanField(default=True, verbose_name='Use SSL')),
                ('folder', models.CharField(max_length=30, verbose_name='Email Folder')),
                ('retrieval_interval', models.IntegerField(blank=True, default='5', null=True, verbose_name='Email Check Interval')),
                ('last_check', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Subject')),
                ('issue', models.CharField(max_length=200, verbose_name='Issue')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 16, 45, 19, 243109, tzinfo=utc), verbose_name='Created')),
                ('modified', models.DateTimeField(blank=True, verbose_name='Modified')),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Open'), (2, 'Reopened'), (3, 'Resolved'), (4, 'Closed'), (5, 'Duplicate')], default=0, verbose_name='Status')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='Resolution')),
                ('priority', models.IntegerField(blank=3, choices=[(1, '1. Critical'), (2, '2. High'), (3, '3. Normal'), (4, '4. Low'), (5, '5. Very Low')], default=3, verbose_name='Priority')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due on')),
                ('secret_key', models.CharField(default=tickets.models.mk_secret, max_length=36, verbose_name='Secret key')),
                ('associated_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.employees', verbose_name='Employees')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.category', verbose_name='Category')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.container', verbose_name='Container')),
                ('master_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ('id',),
                'get_latest_by': 'created',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='email_box',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tickets.email'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 4, 20, 16, 45, 19, 258732, tzinfo=utc), verbose_name='Date')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('public', models.BooleanField(blank=True, default=False, null=True, verbose_name='Tech Only')),
                ('time_spent', models.DurationField(blank=True, null=True)),
                ('google_api', models.BooleanField(default=False)),
                ('verizon_api', models.BooleanField(default=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'ordering': ('-date',),
            },
        ),
    ]
