# Generated by Django 3.2 on 2021-04-14 04:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 4, 35, 33, 472657, tzinfo=utc), verbose_name='Date'),
        ),
    ]
