# Generated by Django 3.2 on 2021-04-14 04:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='google_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='verizon_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 4, 44, 6, 285136, tzinfo=utc), verbose_name='Date'),
        ),
    ]
