# Generated by Django 3.2 on 2021-04-20 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20210420_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='master_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tickets.comment', verbose_name='Master Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.TextField(blank=True, null=True, verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 20, 22, 11, 2, 727499, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 20, 22, 11, 2, 711872, tzinfo=utc), verbose_name='Created'),
        ),
    ]
