# Generated by Django 3.2 on 2021-04-16 23:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20210416_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 16, 23, 15, 12, 189448, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 16, 23, 15, 12, 188448, tzinfo=utc), verbose_name='Created'),
        ),
    ]
