# Generated by Django 3.2 on 2021-04-23 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20210422_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 23, 18, 8, 40, 854125, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 23, 18, 8, 40, 851125, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='issue',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Issue'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Subject'),
        ),
    ]
